// Command mcp-inventory generates a Markdown inventory of every MCP tool
// registered in agent-setup. Run from a CI step on every PR; the generated
// file lives at docs/mcp-inventory.md and should be checked in so reviewers
// can see schema-level changes in code review.
//
//	go run ./cmd/mcp-inventory > ../docs/mcp-inventory.md
//
// The inventory is built from the same platforms.All() registry the runtime
// uses, so it is impossible for the docs to drift from the registered tools.
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/teslashibe/agent-setup/backend/internal/mcp"
	"github.com/teslashibe/agent-setup/backend/internal/mcp/platforms"
)

func main() {
	if err := run(os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, "mcp-inventory:", err)
		os.Exit(1)
	}
}

func run(out io.Writer) error {
	plugins := platforms.All()
	bindings := make([]mcp.PlatformBinding, 0, len(plugins))
	for _, p := range plugins {
		bindings = append(bindings, p.Binding)
	}
	registry, err := mcp.NewRegistry(bindings...)
	if err != nil {
		return fmt.Errorf("registry: %w", err)
	}

	type toolRow struct {
		Name        string
		Description string
		Wraps       string
		Schema      map[string]any
	}
	byPlatform := map[string][]toolRow{}
	platformList := registry.Platforms()

	for _, p := range platformList {
		binding, _ := registry.Binding(p)
		for _, t := range binding.Provider.Tools() {
			byPlatform[p] = append(byPlatform[p], toolRow{
				Name:        t.Name,
				Description: t.Description,
				Wraps:       t.WrapsMethod,
				Schema:      t.InputSchema,
			})
		}
	}

	var totalTools int
	for _, rows := range byPlatform {
		totalTools += len(rows)
	}
	sort.Strings(platformList)

	fmt.Fprintf(out, "# MCP tool inventory\n\n")
	fmt.Fprintf(out, "_Generated by `cmd/mcp-inventory` on %s. Do not edit by hand — re-run after any tool change._\n\n",
		time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(out, "**Platforms:** %d  ·  **Tools:** %d\n\n", len(platformList), totalTools)

	fmt.Fprintf(out, "| Platform | Tools |\n|---|---:|\n")
	for _, p := range platformList {
		fmt.Fprintf(out, "| `%s` | %d |\n", p, len(byPlatform[p]))
	}
	fmt.Fprintln(out)

	for _, p := range platformList {
		rows := byPlatform[p]
		sort.Slice(rows, func(i, j int) bool { return rows[i].Name < rows[j].Name })
		fmt.Fprintf(out, "## `%s` (%d tools)\n\n", p, len(rows))
		for _, r := range rows {
			fmt.Fprintf(out, "### `%s`\n\n", r.Name)
			fmt.Fprintf(out, "%s\n\n", r.Description)
			if r.Wraps != "" {
				fmt.Fprintf(out, "Wraps: `*Client.%s`\n\n", r.Wraps)
			}
			fmt.Fprintln(out, "Input schema:")
			fmt.Fprintln(out)
			fmt.Fprintln(out, "```json")
			indent, _ := json.MarshalIndent(stableSchema(r.Schema), "", "  ")
			fmt.Fprintln(out, strings.TrimSpace(string(indent)))
			fmt.Fprintln(out, "```")
			fmt.Fprintln(out)
		}
	}
	return nil
}

// stableSchema rewrites the raw jsonschema map so the output is
// deterministic — sorts keys, strips a couple of redundant top-level
// metadata fields jsonschema injects.
func stableSchema(in map[string]any) map[string]any {
	if in == nil {
		return nil
	}
	delete(in, "$schema")
	delete(in, "$id")
	return in
}
